#!/usr/bin/env python3
"""Generate FallbackWeights.kt from ml/fallback_weights.json after training."""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "ml" / "fallback_weights.json"
OUT = REPO / "app" / "src" / "main" / "java" / "com" / "dirk" / "kalshiodds" / "prediction" / "FallbackWeights.kt"


def fmt_float_arr(vals, indent=8):
    pad = " " * indent
    chunks = []
    line = pad
    for i, v in enumerate(vals):
        piece = f"{float(v):.8g}f, "
        if len(line) + len(piece) > 100:
            chunks.append(line.rstrip())
            line = pad + piece
        else:
            line += piece
    if line.strip():
        chunks.append(line.rstrip().rstrip(","))
    else:
        chunks.append(pad)
    return "\n".join(chunks)


def fmt_matrix(mat, indent=8):
    # mat is list[list] shape [in, out] — Kotlin Array(in) { FloatArray(out) }
    rows = []
    pad = " " * indent
    for row in mat:
        inner = ", ".join(f"{float(v):.8g}f" for v in row)
        rows.append(f"{pad}floatArrayOf({inner})")
    return ",\n".join(rows)


def main() -> None:
    data = json.loads(SRC.read_text())
    layers = data["layers"]
    assert len(layers) == 3, layers
    mean = data["scaler_mean"]
    std = data["scaler_std"]
    w1, b1 = layers[0]["kernel"], layers[0]["bias"]
    w2, b2 = layers[1]["kernel"], layers[1]["bias"]
    w3, b3 = layers[2]["kernel"], layers[2]["bias"]

    kt = f'''package com.dirk.kalshiodds.prediction

/**
 * Embedded MLP weights mirroring the trained TFLite graph
 * Input(8)->Dense(32,relu)->Dense(16,relu)->Dense(2,softmax).
 * Auto-generated by ml/export_fallback_kt.py — do not hand-edit.
 * Softmax order: [P(NO), P(YES)].
 */
object FallbackWeights {{
    val MEAN = floatArrayOf(
{fmt_float_arr(mean)}
    )
    val STD = floatArrayOf(
{fmt_float_arr(std)}
    )

    private val w1 = arrayOf(
{fmt_matrix(w1)}
    )
    private val b1 = floatArrayOf(
{fmt_float_arr(b1)}
    )
    private val w2 = arrayOf(
{fmt_matrix(w2)}
    )
    private val b2 = floatArrayOf(
{fmt_float_arr(b2)}
    )
    private val w3 = arrayOf(
{fmt_matrix(w3)}
    )
    private val b3 = floatArrayOf(
{fmt_float_arr(b3)}
    )

    fun forward(x: FloatArray): FloatArray {{
        val h1 = denseRelu(x, w1, b1)
        val h2 = denseRelu(h1, w2, b2)
        val logits = denseLinear(h2, w3, b3)
        return softmax(logits)
    }}

    private fun denseRelu(x: FloatArray, w: Array<FloatArray>, b: FloatArray): FloatArray {{
        val out = FloatArray(b.size)
        for (j in b.indices) {{
            var s = b[j]
            for (i in x.indices) s += x[i] * w[i][j]
            out[j] = if (s > 0f) s else 0f
        }}
        return out
    }}

    private fun denseLinear(x: FloatArray, w: Array<FloatArray>, b: FloatArray): FloatArray {{
        val out = FloatArray(b.size)
        for (j in b.indices) {{
            var s = b[j]
            for (i in x.indices) s += x[i] * w[i][j]
            out[j] = s
        }}
        return out
    }}

    private fun softmax(logits: FloatArray): FloatArray {{
        val max = logits.maxOrNull() ?: 0f
        var sum = 0.0
        val exps = DoubleArray(logits.size) {{ i ->
            val v = kotlin.math.exp((logits[i] - max).toDouble())
            sum += v
            v
        }}
        return FloatArray(logits.size) {{ i -> (exps[i] / sum).toFloat() }}
    }}
}}
'''
    OUT.write_text(kt)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
